---
- hosts: all
  become: true

  tasks:  
    - name: Install Docker and Dependencies
      include_tasks: tasks/docker.yml

    - name: Install Kind, kubectl and Create Kind Clusters
      include_tasks: tasks/kind.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Get kubeconfig
      include_tasks: tasks/kubeconfig.yml

    - name: Install and Configure ArgoCD
      include_tasks: tasks/argo.yml    

    - name: Install Helm and Manage Repositories
      include_tasks: tasks/helm.yml

    - name: Install and Configure Vault
      include_tasks: tasks/vault.yml

    - name: Save Istio Remote Secret File
      include_tasks: tasks/remote-secret.yml        

    - name: Install cert-manager
      include_tasks: tasks/cert-manager.yml  

    - name: Install vault-issuer
      include_tasks: tasks/vault-issuer.yml      

    - name: Install cert-manager-istio-csr
      include_tasks: tasks/cert-manager-istio-csr.yml 

    - name: Setup Istio
      include_tasks: tasks/istio.yml
