---

- name: Check if Kind kubeconfig exists
  stat:
    path: "/home/vagrant/kubeconfig-kind"
  register: kubeconfig_stat
  delegate_to: "{{ inventory_hostname }}"

- name: Generate Kind kubeconfig (if not already present)
  shell: kind --name {{ inventory_hostname }} get kubeconfig
  when: kubeconfig_stat.stat.exists == false  # Only run if the file doesn't exist
  register: kubeconfig_output
  delegate_to: "{{ inventory_hostname }}"

- name: Write the kubeconfig to a file
  copy:
    content: "{{ kubeconfig_output.stdout }}"
    dest: "/home/vagrant/kubeconfig-kind"
  when: kubeconfig_stat.stat.exists == false  # Only write if the file doesn't exist
  delegate_to: "{{ inventory_hostname }}"

- name: Fetch Kind kubeconfig from VM to Host
  fetch:
    src: "/home/vagrant/kubeconfig-kind"
    dest: "./{{ inventory_hostname }}/kubeconfig"
    flat: yes  # Ensures that the file is saved directly without extra directory structure
  delegate_to: "{{ inventory_hostname }}"