---

- name: Get kubeconfig for cluster
  command: kind get kubeconfig --name {{ inventory_hostname }}
  register: cluster_kubeconfig

- name: Retrieve cluster API endpoint
  command: kubectl config view --raw --minify -o jsonpath='{.clusters[0].cluster.server}' --context kind-{{ inventory_hostname }}
  register: cluster_api_endpoint  

- name: Base64 encode the kubeconfig for cluster
  shell: echo "{{ cluster_kubeconfig.stdout }}" | base64 | tr -d '\n'
  register: kubeconfig_b64    

- name: Create Istio-compatible secret YAML
  copy:
    dest: ./{{ inventory_hostname }}/{{ inventory_hostname }}-cluster-secret.yaml
    content: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: istio-remote-cluster
        namespace: istio-system
      data:
        # Base64-encoded kubeconfig for the cluster
        kubeconfig: "{{ kubeconfig_b64.stdout }}"   